import Link from 'next/link'

export const metadata = {
  title: 'Disclaimer — LegalSaathi',
  description: 'What LegalSaathi is, what it is not, and its limits.',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-rule">
        <div className="max-w-[720px] mx-auto px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <span className="w-5 h-5 rounded-full border-[1.5px] border-tape" />
            <span className="font-serif text-xl">
              Legal<em className="italic text-tape">Saathi</em>
            </span>
          </Link>
        </div>
      </header>

      <main className="max-w-[720px] mx-auto px-6 py-14 pb-24">
        <p className="font-mono text-[11px] tracking-[0.13em] uppercase text-tape mb-4">
          § Disclaimer
        </p>
        <h1 className="font-serif text-4xl leading-[1.05] tracking-tight mb-3">
          Read this before you rely on anything here.
        </h1>
        <p className="text-ink-soft text-[16px] leading-[1.7] mb-12">
          LegalSaathi exists to help you understand your situation well enough to
          take the next step. It is not a lawyer, and this page explains exactly
          where its limits are.
        </p>

        <div className="flex flex-col gap-9">
          <Section n="01" title="This is information, not advice">
            Legal advice means a qualified lawyer applying the law to your specific
            facts and taking professional responsibility for that judgment.
            LegalSaathi does none of those things. It explains what the law says in
            general terms. No lawyer-client relationship is created by using this
            site, and nothing here is privileged or confidential in the legal sense.
          </Section>

          <Section n="02" title="It can be wrong">
            Answers are generated by an AI model working from statutory text stored
            in our database. That text may be out of date, may have been amended,
            or may not be the provision that actually governs your case. The model
            can also misread what it retrieves. Every answer shows the sections it
            drew on precisely so you can check them yourself — please do.
          </Section>

          <Section n="03" title="Coverage is limited">
            LegalSaathi currently holds the Consumer Protection Act, 2019 and the
            Bharatiya Nagarik Suraksha Sanhita, 2023. Anything outside those — most
            tenancy, employment, family, and property law — has no statutory
            grounding here, and Saathi will tell you so rather than guess. Many
            areas of Indian law also vary by state.
          </Section>

          <Section n="04" title="Time limits are real and unforgiving">
            Most legal remedies expire. Consumer complaints, appeals, and criminal
            complaints all carry deadlines, and missing one can end your claim
            permanently regardless of how strong it was. Do not treat anything here
            as a reason to wait.
          </Section>

          <Section n="05" title="When to stop reading and call someone">
            If you are facing arrest, violence, threats, a court date, a large
            financial loss, or anything involving a child — speak to a lawyer.
            Free legal aid is available to most people in India through your
            District Legal Services Authority, and you do not have to be able to
            pay.
          </Section>

          <Section n="06" title="We are not liable">
            LegalSaathi is provided as is. We accept no liability for any loss
            arising from your reliance on it. You use it at your own risk, and any
            decision you take remains yours.
          </Section>
        </div>

        <div className="mt-14 bg-ink text-paper rounded-[3px] px-8 py-7">
          <p className="font-serif text-[21px] leading-snug mb-2">
            If you take one thing from this page:
          </p>
          <p className="text-[15px] leading-[1.7] text-paper/70">
            Use Saathi to understand your situation and to walk into a lawyer&apos;s
            office knowing what to ask. Do not use it as a substitute for that
            conversation.
          </p>
        </div>

        <p className="text-[12.5px] text-ink-mute mt-10">
          Last updated 15 August 2026.
        </p>
      </main>
    </div>
  )
}

function Section({
  n,
  title,
  children,
}: {
  n: string
  title: string
  children: React.ReactNode
}) {
  return (
    <div className="flex gap-5">
      <span className="font-mono text-[11px] text-tape pt-1.5 shrink-0">§ {n}</span>
      <div>
        <h2 className="font-serif text-[23px] leading-tight mb-2">{title}</h2>
        <p className="text-[15px] leading-[1.72] text-ink-soft">{children}</p>
      </div>
    </div>
  )
}   